apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worklog-backend
  template:
    metadata:
      labels:
        app: worklog-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: worklog-backend
          image: sysnet4admin/worklog-backend:e838cf26
          ports:
            - containerPort: 80
          env:
            - name: MONGO_HOST
              value: worklog-mongodb.default.svc.cluster.local
            - name: IMAGE_TAG
              value: buildtest1
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: worklog-mongodb-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worklog-mongodb-creds
                  key: password
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: worklog-backend
spec:
  selector:
    app: worklog-backend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: worklog-backend
spec:
  parentRefs:
    - name: nginx-gateway
  hostnames:
    - worklog-backend.myk8s.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: worklog-backend
          port: 80
