apiVersion: v1
kind: Secret
metadata:
  name: worklog-mongodb-creds
type: Opaque
stringData:
  username: root
  password: mypassw0rd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worklog-mongodb
  template:
    metadata:
      labels:
        app: worklog-mongodb
    spec:
      containers:
        - name: worklog-mongodb
          image: mongo:8.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: worklog-mongodb-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worklog-mongodb-creds
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: worklog-mongodb
spec:
  selector:
    app: worklog-mongodb
  ports:
    - port: 27017
      targetPort: 27017
