name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.run-test.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        id: run-test
        run: |
          echo "let's run a test"
          echo "result=passed" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: ["test"]
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        id: build-image
        run: |
          echo "test result: ${{ needs.test.outputs.result }}"
          echo "Let's build the image"
          echo "image=worklog-backend:${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          exit 1
  deploy:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy image
        run: |
          echo "Let's deploy the image: ${{ needs.build.outputs.image }}"
  notify-success:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: ${{ success() }}
    steps:
      - name: Notify success
        run: |
          echo "SUCCESS: ${{ needs.build.outputs.image }}"
  notify-failure:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: ${{ failure() }}
    steps:
      - name: Notify failure
        run: |
          echo "FAILURE: build result is ${{ needs.build.result }}"
